default: &default
  adapter: postgresql
  endcoding: utf-8
  host: localhost
  pool: 5
  user: postgres
  password: postgres....

development:
  <<: *default
  database: pagernova_development

test:
  <<: *default
  database: pagernova_development
